x-logging-common: &logging-common
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  db:
    image: postgres:18-alpine
    command: postgres -c 'max_connections=300'
    container_name: ugc-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    <<: *logging-common

  web:
    container_name: ugc-web
    build:
      context: .
      dockerfile: "Dockerfile"
    command: [
        "bash",
        "-c",
        "python manage.py collectstatic --no-input
        && python manage.py migrate
        && python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000",
      ]
    ports:
      - "8000:8000"
      - "5678:5678"
    restart: always
    env_file:
      - ./.env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    <<: *logging-common

  redis:
    image: redis:7-alpine
    container_name: ugc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
    <<: *logging-common

volumes:
  pgdata:
  static_volume:
  media_volume:
  redis_data:
