# Generated by Django 5.2 on 2026-04-07 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ugc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_answers",
                    models.IntegerField(
                        default=0,
                        help_text="Количество ответов на данный вопрос",
                    ),
                ),
                (
                    "custom_answers_count",
                    models.IntegerField(
                        default=0,
                        help_text="Количество собственных ответов (не из вариантов)",
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="ugc.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_statistics",
            },
        ),
        migrations.CreateModel(
            name="AnswerOptionStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "times_selected",
                    models.IntegerField(
                        default=0, help_text="Сколько раз выбран этот вариант"
                    ),
                ),
                (
                    "option",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="ugc.answeroption",
                    ),
                ),
            ],
            options={
                "db_table": "answer_option_statistics",
                "indexes": [
                    models.Index(
                        fields=["times_selected"],
                        name="answer_opti_times_s_9cb941_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PollStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_completed_sessions",
                    models.IntegerField(
                        default=0,
                        help_text="Количество завершённых прохождений опроса",
                    ),
                ),
                (
                    "total_answers",
                    models.IntegerField(
                        default=0,
                        help_text="Общее количество ответов на все вопросы",
                    ),
                ),
                (
                    "average_completion_time_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Среднее время прохождения (сек)",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "poll",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="ugc.poll",
                    ),
                ),
            ],
            options={
                "db_table": "poll_statistics",
                "indexes": [
                    models.Index(
                        fields=["total_answers"],
                        name="poll_statis_total_a_8d179e_idx",
                    )
                ],
            },
        ),
    ]
